---
title: "<span style='font-size:125%;color:#CA1010'>Dades Educació</span style='color:#CA1010'>"
subtitle: "I'll be back"
author:
  - Marcos Montoro^[telecomontoro@uoc.edu] - Gaby Ramirez

date: "`r Sys.Date()`"
output: html_document
    
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = paste0("../Informe Comentaris/",format(Sys.Date(),"%Y-%m-%d"),"_Informe.html")) })




---


```{css sidenote, echo = FALSE}
.main-container {
  width: 98%;
  margin-left: 1%;
  margin-right: 1%;
}



#TOC {
  z-index: 2;
 }
 
 
 <style>
#my-table {
  position: fixed;
  top: 100px;
  left: 100px;
}
</style>
 
 
```



```{r echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = F,
                      warning = F)
#llibreries

if(require("pacman")=="FALSE"){
  install.packages('pacman')
  library('pacman')
  pacman::p_load(magrittr,readr,tokenizers,lubridate,tidyr,tidyverse,dplyr,corrpnlot,ggplot2,data.table,ggpubr,devtools,gplots) 
} else {
  library('pacman')
  pacman::p_load(magrittr,readr,lubridate,tokenizers,tidyr,tidyverse,dplyr,corrplot,ggplot2,data.table,ggpubr,devtools,gplots) 
}
p_loaded()  

options(scipen=999)

library(tidyverse) # Inclou dplyr, ggplot2 i altres llibreries
library(tidytext) # Llibreria per a l'anàlisi de text
library(stopwords) # Llibreria de stopwords
library(sentimentr)
library(readxl)
library(xlsx)
library(wordcloud)
library(dplyr)
library(DT)

```



```{r include=FALSE, warning=F, eval=T}
library(stringr)
library(Hmisc)
library(data.table)
library(lubridate)
library(gtools)
library(magrittr)
library(tidyr)
library(tidyverse)
library(compareGroups)
library(kableExtra)
library(plotly)
library(reshape2)
```

```{r}




read_txt_to_df <- function(file_path) {
  # Llegir totes les línies del fitxer
  lines <- readLines(file_path)
  
  # Crear un dataframe buit amb les columnes especificades
  df <- data.frame(Centre = character(), Especialitat = character(), Jornada = character(), Data_Ini = character(), Data_fi = character(), Substitut = character(), stringsAsFactors=FALSE)
  
  for (i in 1:length(lines)) {
    if (grepl("^Institut", lines[i])) {
      centre <- unlist(strsplit(lines[i], "\t"))[1]
      especialitat <- unlist(strsplit(lines[i], "\t"))[2]
      jornada <- unlist(strsplit(lines[i], "\t"))[3]
      data_ini <- unlist(strsplit(lines[i], "\t"))[4]
      data_fi <- unlist(strsplit(lines[i], "\t"))[5]
      # Buscar el substitut en la línia següent que comença amb "Substitut/a:"
      if (i+1 <= length(lines) && grepl("^Substitut/a:", lines[i+1])) {
        substitut <- gsub("Substitut/a:\\t?", "", lines[i+1])
      } else {
        substitut <- NA
      }
      # Afegir les dades al dataframe
      df <- rbind(df, data.frame(Institut = centre, 
                                 Especialitat = especialitat, 
                                 Jornada = jornada, 
                                 Data_Ini = data_ini, 
                                 Data_fi = data_fi, 
                                 Substitut = substitut))
    }
  }
  
  return(df)
}

# Obtenir una llista de tots els fitxers .txt en el directori 'Data'
file_list <- list.files(path = "../Data", pattern = "\\.txt$", full.names = TRUE)

# Crear un llistat on emmagatzemarem els dataframes de cada fitxer
df_list <- list()

# Iterar sobre cada fitxer i aplicar la funció
for (file in file_list) {
  df <- read_txt_to_df(file)
  df_list[[file]] <- df
}

# Si vols combinar tots els dataframes en un sol dataframe (suposant que tots tenen la mateixa estructura)
df <- do.call(rbind, df_list)
rownames(df) <- 1:nrow(df)



# Extractar el text dins dels parèntesis en la columna 'Institut'
df$Poblacio <- str_extract(df$Institut, "\\(([^)]+)\\)")


# Eliminar els caràcters '(' i ')' de la columna 'Poblacio'
df$Poblacio <- str_replace_all(df$Poblacio, "[()]", "")

# Eliminar la informació dins dels parèntesis (incloent-hi els parèntesis) de la columna 'Centre'
df$Institut <- str_replace(df$Institut, "\\s*\\([^)]+\\)", "")





# Convertir les columnes 'Data_Ini' i 'Data_fi' a format de data
df$Data_Ini <- as.Date(df$Data_Ini, format = "%d/%m/%y")
df$Data_fi <- as.Date(df$Data_fi, format = "%d/%m/%y")

df$Substitut[df$Substitut == ""] <- NA



```









# Plaçes sense cobrir Institut


```{r}


df_analisi <- df %>%
  group_by(Institut) %>%
  summarise(
    Places_Sortides = n(),
    Places_Sense_Cobrir = sum(is.na(Substitut), na.rm = TRUE)
  ) %>%
  arrange(desc(Places_Sortides)) %>%
  mutate(Institut_ordered = factor(Institut, levels = Institut))

df_analisi %>%
  plot_ly(x = ~Institut_ordered, y = ~Places_Sortides, type = 'bar', name = 'Places Sortides') %>%
  add_trace(y = ~Places_Sense_Cobrir, name = 'Places Sense Cobrir', type = 'bar') %>%
  layout(title = 'Anàlisi de Places per Institut', barmode = 'group', xaxis = list(tickangle = -45))



```







```{r}


# Taules per a cada tipus de Jornada
df_sencera <- df %>%
  filter(Jornada == "Sencera") %>%
  group_by(Institut) %>%
  summarise(
    Places_Sortides_Sencera = n(),
    Places_Sense_Cobrir_Sencera = sum(is.na(Substitut), na.rm = TRUE)
  ) %>%
  mutate(
    Proporcio_Sencera = Places_Sense_Cobrir_Sencera / Places_Sortides_Sencera,
    Places_Sense_Cobrir_Sencera = paste0(Places_Sense_Cobrir_Sencera, " (", scales::percent(Proporcio_Sencera, accuracy = 1), ")")
  )

df_mig <- df %>%
  filter(Jornada == "0,50") %>%
  group_by(Institut) %>%
  summarise(
    Places_Sortides_Mig = n(),
    Places_Sense_Cobrir_Mig = sum(is.na(Substitut), na.rm = TRUE)
  ) %>%
  mutate(
    Proporcio_Mig = Places_Sense_Cobrir_Mig / Places_Sortides_Mig,
    Places_Sense_Cobrir_Mig = paste0(Places_Sense_Cobrir_Mig, " (", scales::percent(Proporcio_Mig, accuracy = 1), ")")
  )

# Unir les taules
df_analisi <- full_join(df_sencera, df_mig, by = "Institut") %>%
  mutate(
    Places_Sortides_Sencera = coalesce(Places_Sortides_Sencera, 0),
    Places_Sense_Cobrir_Sencera = coalesce(Places_Sense_Cobrir_Sencera, "0 (0%)"),
    Places_Sortides_Mig = coalesce(Places_Sortides_Mig, 0),
    Places_Sense_Cobrir_Mig = coalesce(Places_Sense_Cobrir_Mig, "0 (0%)")
  )

# Eliminar columnes de proporcions
df_analisi$Proporcio_Sencera <- NULL
df_analisi$Proporcio_Mig <- NULL

df_analisi$Total_Ofertada <- df_analisi$Places_Sortides_Sencera + df_analisi$Places_Sortides_Mig
# Extreu els números de les columnes i converteix-los en numèrics
df_analisi <- df_analisi %>%
  mutate(
    Numeric_Sense_Cobrir_Sencera = as.numeric(str_extract(Places_Sense_Cobrir_Sencera, "^[0-9]+")),
    Numeric_Sense_Cobrir_Mig = as.numeric(str_extract(Places_Sense_Cobrir_Mig, "^[0-9]+"))
  )

# Suma les columnes i desa el resultat a Sense_Cobrir
df_analisi$Sense_Cobrir <- df_analisi$Numeric_Sense_Cobrir_Sencera + df_analisi$Numeric_Sense_Cobrir_Mig
df_analisi$Sense_Cobrir <- paste0(df_analisi$Sense_Cobrir , " (", scales::percent(df_analisi$Sense_Cobrir / df_analisi$Total_Ofertada, accuracy = 1), ")")

# (Opcional) Pots eliminar les columnes intermèdies si no les necessites
df_analisi$Numeric_Sense_Cobrir_Sencera <- NULL
df_analisi$Numeric_Sense_Cobrir_Mig <- NULL

datatable(df_analisi, 
          options = list(pageLength = 5, autoWidth = TRUE),
          caption = "Anàlisi de Places per Institut")


write.csv2(df_analisi,
           "../Informe comentaris/Instituts.csv",
           row.names =  F,
            fileEncoding = "ISO-8859-1")


```









# Plaçes sense cobrir especialitat



```{r}


df %>%
  group_by(Especialitat) %>%
  summarise(
    Places_Sortides = n(),
    Places_Sense_Cobrir = sum(is.na(Substitut), na.rm = TRUE)
  ) %>%
  arrange(desc(Places_Sortides)) %>%
  mutate(Especialitat = factor(Especialitat, levels = Especialitat)) %>%
  plot_ly(x = ~Especialitat, y = ~Places_Sortides, type = 'bar', name = 'Places Sortides') %>%
  add_trace(y = ~Places_Sense_Cobrir, name = 'Places Sense Cobrir', type = 'bar') %>%
  layout(title = 'Anàlisi de Places per Especialitat', barmode = 'group', xaxis = list(tickangle = -45))


```



```{r}


# Taules per a cada tipus de Jornada
df_sencera <- df %>%
  filter(Jornada == "Sencera") %>%
  group_by(Especialitat) %>%
  summarise(
    Places_Sortides_Sencera = n(),
    Places_Sense_Cobrir_Sencera = sum(is.na(Substitut), na.rm = TRUE)
  ) %>%
  mutate(
    Proporcio_Sencera = Places_Sense_Cobrir_Sencera / Places_Sortides_Sencera,
    Places_Sense_Cobrir_Sencera = paste0(Places_Sense_Cobrir_Sencera, " (", scales::percent(Proporcio_Sencera, accuracy = 1), ")")
  )

df_mig <- df %>%
  filter(Jornada == "0,50") %>%
  group_by(Especialitat) %>%
  summarise(
    Places_Sortides_Mig = n(),
    Places_Sense_Cobrir_Mig = sum(is.na(Substitut), na.rm = TRUE)
  ) %>%
  mutate(
    Proporcio_Mig = Places_Sense_Cobrir_Mig / Places_Sortides_Mig,
    Places_Sense_Cobrir_Mig = paste0(Places_Sense_Cobrir_Mig, " (", scales::percent(Proporcio_Mig, accuracy = 1), ")")
  )

# Unir les taules
df_analisi <- full_join(df_sencera, df_mig, by = "Especialitat") %>%
  mutate(
    Places_Sortides_Sencera = coalesce(Places_Sortides_Sencera, 0),
    Places_Sense_Cobrir_Sencera = coalesce(Places_Sense_Cobrir_Sencera, "0 (0%)"),
    Places_Sortides_Mig = coalesce(Places_Sortides_Mig, 0),
    Places_Sense_Cobrir_Mig = coalesce(Places_Sense_Cobrir_Mig, "0 (0%)")
  )

# Eliminar columnes de proporcions
df_analisi$Proporcio_Sencera <- NULL
df_analisi$Proporcio_Mig <- NULL

df_analisi$Total_Ofertada <- df_analisi$Places_Sortides_Sencera + df_analisi$Places_Sortides_Mig
# Extreu els números de les columnes i converteix-los en numèrics
df_analisi <- df_analisi %>%
  mutate(
    Numeric_Sense_Cobrir_Sencera = as.numeric(str_extract(Places_Sense_Cobrir_Sencera, "^[0-9]+")),
    Numeric_Sense_Cobrir_Mig = as.numeric(str_extract(Places_Sense_Cobrir_Mig, "^[0-9]+"))
  )

# Suma les columnes i desa el resultat a Sense_Cobrir
df_analisi$Sense_Cobrir <- df_analisi$Numeric_Sense_Cobrir_Sencera + df_analisi$Numeric_Sense_Cobrir_Mig
df_analisi$Sense_Cobrir <- paste0(df_analisi$Sense_Cobrir , " (", scales::percent(df_analisi$Sense_Cobrir / df_analisi$Total_Ofertada, accuracy = 1), ")")

# (Opcional) Pots eliminar les columnes intermèdies si no les necessites
df_analisi$Numeric_Sense_Cobrir_Sencera <- NULL
df_analisi$Numeric_Sense_Cobrir_Mig <- NULL

datatable(df_analisi, 
          options = list(pageLength = 5, autoWidth = TRUE),
          caption = "Anàlisi de Places per Especialitat")



write.csv2(df_analisi,
           "../Informe comentaris/Especialitat.csv",
           row.names =  F,
            fileEncoding = "ISO-8859-1")


```







# Plaçes sense cobrir Població




```{r}


df %>%
  group_by(Poblacio) %>%
  summarise(
    Places_Sortides = n(),
    Places_Sense_Cobrir = sum(is.na(Substitut), na.rm = TRUE)
  ) %>%
  arrange(desc(Places_Sortides)) %>%
  mutate(Especialitat = factor(Poblacio, levels = Poblacio)) %>%
  plot_ly(x = ~Poblacio, y = ~Places_Sortides, type = 'bar', name = 'Places Sortides') %>%
  add_trace(y = ~Places_Sense_Cobrir, name = 'Places Sense Cobrir', type = 'bar') %>%
  layout(title = 'Anàlisi de Places per Població', barmode = 'group', xaxis = list(tickangle = -45))


```

```{r}


# Taules per a cada tipus de Jornada
df_sencera <- df %>%
  filter(Jornada == "Sencera") %>%
  group_by(Poblacio) %>%
  summarise(
    Places_Sortides_Sencera = n(),
    Places_Sense_Cobrir_Sencera = sum(is.na(Substitut), na.rm = TRUE)
  ) %>%
  mutate(
    Proporcio_Sencera = Places_Sense_Cobrir_Sencera / Places_Sortides_Sencera,
    Places_Sense_Cobrir_Sencera = paste0(Places_Sense_Cobrir_Sencera, " (", scales::percent(Proporcio_Sencera, accuracy = 1), ")")
  )

df_mig <- df %>%
  filter(Jornada == "0,50") %>%
  group_by(Poblacio) %>%
  summarise(
    Places_Sortides_Mig = n(),
    Places_Sense_Cobrir_Mig = sum(is.na(Substitut), na.rm = TRUE)
  ) %>%
  mutate(
    Proporcio_Mig = Places_Sense_Cobrir_Mig / Places_Sortides_Mig,
    Places_Sense_Cobrir_Mig = paste0(Places_Sense_Cobrir_Mig, " (", scales::percent(Proporcio_Mig, accuracy = 1), ")")
  )

# Unir les taules
df_analisi <- full_join(df_sencera, df_mig, by = "Poblacio") %>%
  mutate(
    Places_Sortides_Sencera = coalesce(Places_Sortides_Sencera, 0),
    Places_Sense_Cobrir_Sencera = coalesce(Places_Sense_Cobrir_Sencera, "0 (0%)"),
    Places_Sortides_Mig = coalesce(Places_Sortides_Mig, 0),
    Places_Sense_Cobrir_Mig = coalesce(Places_Sense_Cobrir_Mig, "0 (0%)")
  )

# Eliminar columnes de proporcions
df_analisi$Proporcio_Sencera <- NULL
df_analisi$Proporcio_Mig <- NULL

df_analisi$Total_Ofertada <- df_analisi$Places_Sortides_Sencera + df_analisi$Places_Sortides_Mig
# Extreu els números de les columnes i converteix-los en numèrics
df_analisi <- df_analisi %>%
  mutate(
    Numeric_Sense_Cobrir_Sencera = as.numeric(str_extract(Places_Sense_Cobrir_Sencera, "^[0-9]+")),
    Numeric_Sense_Cobrir_Mig = as.numeric(str_extract(Places_Sense_Cobrir_Mig, "^[0-9]+"))
  )

# Suma les columnes i desa el resultat a Sense_Cobrir
df_analisi$Sense_Cobrir <- df_analisi$Numeric_Sense_Cobrir_Sencera + df_analisi$Numeric_Sense_Cobrir_Mig
df_analisi$Sense_Cobrir <- paste0(df_analisi$Sense_Cobrir , " (", scales::percent(df_analisi$Sense_Cobrir / df_analisi$Total_Ofertada, accuracy = 1), ")")

# (Opcional) Pots eliminar les columnes intermèdies si no les necessites
df_analisi$Numeric_Sense_Cobrir_Sencera <- NULL
df_analisi$Numeric_Sense_Cobrir_Mig <- NULL

datatable(df_analisi, 
          options = list(pageLength = 5, autoWidth = TRUE),
          caption = "Anàlisi de Places per Població")



write.csv2(df_analisi,
           "../Informe comentaris/Població.csv",
           row.names =  F,
            fileEncoding = "ISO-8859-1")


```















# Plaçes sense cobrir Per Jornada



```{r}


df %>%
  group_by(Jornada) %>%
  summarise(
    Places_Sortides = n(),
    Places_Sense_Cobrir = sum(is.na(Substitut), na.rm = TRUE)
  ) %>%
  arrange(desc(Places_Sortides)) %>%
  mutate(Especialitat = factor(Jornada, levels = Jornada)) %>%
  plot_ly(x = ~Jornada, y = ~Places_Sortides, type = 'bar', name = 'Places Sortides') %>%
  add_trace(y = ~Places_Sense_Cobrir, name = 'Places Sense Cobrir', type = 'bar') %>%
  layout(title = 'Anàlisi de Places per Jornada', barmode = 'group', xaxis = list(tickangle = -45))


```

```{r}
df_analisi <- df %>%
  group_by(Jornada) %>%
  summarise(
    Places_Sortides = n(),
    Places_Sense_Cobrir = sum(is.na(Substitut), na.rm = TRUE)
  ) %>%
  mutate(
    Proporcio = Places_Sense_Cobrir / Places_Sortides,
    Places_Sense_Cobrir = paste0(Places_Sense_Cobrir, " (", scales::percent(Proporcio, accuracy = 1), ")")
  ) %>%
  arrange(desc(Places_Sortides))

df_analisi$Proporcio <- NULL

datatable(df_analisi, 
          options = list(pageLength = 5, autoWidth = TRUE),
          caption = "Anàlisi de Places per Jornada")


write.csv2(df_analisi,
           "../Informe comentaris/Jornada.csv",
           row.names =  F,
            fileEncoding = "ISO-8859-1")

```










